<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>../ClipForge.UI/Assets/ClipForge.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>ClipForge.Platform.Windows</RootNamespace>
    <AssemblyName>ClipForge</AssemblyName>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ClipForge.Core/ClipForge.Core.csproj" />
    <ProjectReference Include="../ClipForge.UI/ClipForge.UI.csproj" />
  </ItemGroup>
</Project>